version: 2.1

jobs:
  build-and-test:
    docker:
        - image: circleci/python:3.8
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./test_app.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test