version: 2.1

jobs:
  build-and-test:
    docker:
        - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
          name: Python Dependencies
      - run:
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
          name: Unit Test
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  main:
    jobs:
      - build-and-test